# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AuthorItemNew(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, bio: str=None):  # noqa: E501
        """AuthorItemNew - a model defined in Swagger

        :param name: The name of this AuthorItemNew.  # noqa: E501
        :type name: str
        :param bio: The bio of this AuthorItemNew.  # noqa: E501
        :type bio: str
        """
        self.swagger_types = {
            'name': str,
            'bio': str
        }

        self.attribute_map = {
            'name': 'name',
            'bio': 'bio'
        }

        self._name = name
        self._bio = bio

    @classmethod
    def from_dict(cls, dikt) -> 'AuthorItemNew':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthorItemNew of this AuthorItemNew.  # noqa: E501
        :rtype: AuthorItemNew
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this AuthorItemNew.


        :return: The name of this AuthorItemNew.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AuthorItemNew.


        :param name: The name of this AuthorItemNew.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def bio(self) -> str:
        """Gets the bio of this AuthorItemNew.


        :return: The bio of this AuthorItemNew.
        :rtype: str
        """
        return self._bio

    @bio.setter
    def bio(self, bio: str):
        """Sets the bio of this AuthorItemNew.


        :param bio: The bio of this AuthorItemNew.
        :type bio: str
        """
        if bio is None:
            raise ValueError("Invalid value for `bio`, must not be `None`")  # noqa: E501

        self._bio = bio
