# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.album_item import AlbumItem  # noqa: F401,E501
from swagger_server import util


class AuthorItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, bio: str=None, albums: List[AlbumItem]=None):  # noqa: E501
        """AuthorItem - a model defined in Swagger

        :param id: The id of this AuthorItem.  # noqa: E501
        :type id: str
        :param name: The name of this AuthorItem.  # noqa: E501
        :type name: str
        :param bio: The bio of this AuthorItem.  # noqa: E501
        :type bio: str
        :param albums: The albums of this AuthorItem.  # noqa: E501
        :type albums: List[AlbumItem]
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'bio': str,
            'albums': List[AlbumItem]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'bio': 'bio',
            'albums': 'albums'
        }

        self._id = id
        self._name = name
        self._bio = bio
        self._albums = albums

    @classmethod
    def from_dict(cls, dikt) -> 'AuthorItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthorItem of this AuthorItem.  # noqa: E501
        :rtype: AuthorItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this AuthorItem.


        :return: The id of this AuthorItem.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this AuthorItem.


        :param id: The id of this AuthorItem.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this AuthorItem.


        :return: The name of this AuthorItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this AuthorItem.


        :param name: The name of this AuthorItem.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def bio(self) -> str:
        """Gets the bio of this AuthorItem.


        :return: The bio of this AuthorItem.
        :rtype: str
        """
        return self._bio

    @bio.setter
    def bio(self, bio: str):
        """Sets the bio of this AuthorItem.


        :param bio: The bio of this AuthorItem.
        :type bio: str
        """
        if bio is None:
            raise ValueError("Invalid value for `bio`, must not be `None`")  # noqa: E501

        self._bio = bio

    @property
    def albums(self) -> List[AlbumItem]:
        """Gets the albums of this AuthorItem.


        :return: The albums of this AuthorItem.
        :rtype: List[AlbumItem]
        """
        return self._albums

    @albums.setter
    def albums(self, albums: List[AlbumItem]):
        """Sets the albums of this AuthorItem.


        :param albums: The albums of this AuthorItem.
        :type albums: List[AlbumItem]
        """
        if albums is None:
            raise ValueError("Invalid value for `albums`, must not be `None`")  # noqa: E501

        self._albums = albums
