# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FriendItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, username: str=None, name: str=None, bio: str=None):  # noqa: E501
        """FriendItem - a model defined in Swagger

        :param id: The id of this FriendItem.  # noqa: E501
        :type id: str
        :param username: The username of this FriendItem.  # noqa: E501
        :type username: str
        :param name: The name of this FriendItem.  # noqa: E501
        :type name: str
        :param bio: The bio of this FriendItem.  # noqa: E501
        :type bio: str
        """
        self.swagger_types = {
            'id': str,
            'username': str,
            'name': str,
            'bio': str
        }

        self.attribute_map = {
            'id': 'id',
            'username': 'username',
            'name': 'name',
            'bio': 'bio'
        }

        self._id = id
        self._username = username
        self._name = name
        self._bio = bio

    @classmethod
    def from_dict(cls, dikt) -> 'FriendItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FriendItem of this FriendItem.  # noqa: E501
        :rtype: FriendItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this FriendItem.


        :return: The id of this FriendItem.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this FriendItem.


        :param id: The id of this FriendItem.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def username(self) -> str:
        """Gets the username of this FriendItem.


        :return: The username of this FriendItem.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this FriendItem.


        :param username: The username of this FriendItem.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def name(self) -> str:
        """Gets the name of this FriendItem.


        :return: The name of this FriendItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this FriendItem.


        :param name: The name of this FriendItem.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def bio(self) -> str:
        """Gets the bio of this FriendItem.


        :return: The bio of this FriendItem.
        :rtype: str
        """
        return self._bio

    @bio.setter
    def bio(self, bio: str):
        """Sets the bio of this FriendItem.


        :param bio: The bio of this FriendItem.
        :type bio: str
        """
        if bio is None:
            raise ValueError("Invalid value for `bio`, must not be `None`")  # noqa: E501

        self._bio = bio
